// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKx4Vg14JlPHSAul183UiLO3XMRuQFWk',
    appId: '1:145988143171:web:73226208f9cb3aacc8acf6',
    messagingSenderId: '145988143171',
    projectId: 'mess-management-9efcd',
    authDomain: 'mess-management-9efcd.firebaseapp.com',
    storageBucket: 'mess-management-9efcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVyA7BIbBo6CIUIJ4lgDMQIYE-X6EMo6c',
    appId: '1:145988143171:android:76390314ddfade81c8acf6',
    messagingSenderId: '145988143171',
    projectId: 'mess-management-9efcd',
    storageBucket: 'mess-management-9efcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALo9JQRlWlUMPYDigGRYXANx9DSgyrrCg',
    appId: '1:145988143171:ios:ae2a3870ed20e182c8acf6',
    messagingSenderId: '145988143171',
    projectId: 'mess-management-9efcd',
    storageBucket: 'mess-management-9efcd.appspot.com',
    iosBundleId: 'com.example.messManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALo9JQRlWlUMPYDigGRYXANx9DSgyrrCg',
    appId: '1:145988143171:ios:2c9ed6ad47fc6b6fc8acf6',
    messagingSenderId: '145988143171',
    projectId: 'mess-management-9efcd',
    storageBucket: 'mess-management-9efcd.appspot.com',
    iosBundleId: 'com.example.messManagementApp.RunnerTests',
  );
}
